### PR TITLE
Integration Tests

### PR DESCRIPTION
**Pull request by pritidesai**
Making sure that we are running integration tests as part of Travis.

Updated all the existing integration tests to reflect changes in the underlying methods including its return type.

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
@houshengbo The PR is to improve integration test and address issue #360 . Will you review it ?

**Comment by daisy-ycguo** [comment]
When issue #374 is fixed, we can disable interative mode, other than sending a Y character to the stdin.

**Comment by pritidesai** [comment]
Thanks @daisy-ycguo I have comments in the code itself, to improve on sending "y" on STDIN.

**Comment by pritidesai** [comment]
@daisy-ycguo @lzbj @houshengbo all the integration tests are failing with `{"error":"Missing cmd key"}` what does this error mean? is `utils.Flags.WithinOpenWhisk`  set to `true` in travis builds? wskdeploy still exits with 0 status which is odd.

**Comment by lzbj** [comment]
@pritidesai @daisy-ycguo @houshengbo , use command return code to determine deploy failed or pass is one way  to help improve , but sometimes, even deploy failed, the command could not reflect what really happened or even return success.
To better address this, I suggest we could use wsk cli lib or rest calls to make sure the deploy behavior is what we expected.

**Comment by pritidesai** [comment]
Have decided to fix every failed integration tests in separate PR, still need some code from this PR, specially from wskdeploy.go, I had added timeout enhancement here to  quit "wskdeploy" execution if it takes more than 30 seconds(configurable).

**Pull request closed without merging**
