### PR TITLE
Improve deployment.yml in webhook use case

### PR DESCRIPTION
**Pull request by daisy-ycguo**

### CODE REVIEW

**Comment by pritidesai** [comment]
Hi @daisy-ycguo we have bigger problem running the web hook use case, the way it is specified in manifest and deployment files, fails with arbitrary error (more details in issue #311 )

```
./wskdeploy -m tests/usecases/webhook/manifest.yml -d tests/usecases/webhook/deployment.yml 
2017/08/16 10:46:57 open tests/usecases/webhook/https://raw.githubusercontent.com/apache/incubator-openwhisk-catalog/master/packages/github/webhook.js: no such file or directory
2017/08/16 10:46:57 Error happened during execution, please type 'wskdeploy -h' for help messages.
```

since we have the action file available under `src/`, can you also update the location in the manifest file and make sure wskdeploy is able to deploy web hook use case? If not, please open another issue if wskdeploy fails with valid manifest and deployment files.

**Comment by mrutkows** [comment]
@daisy-ycguo Please verify Priti's assessment that this will not run if a user supplies valid values for the parameters.

**Comment by daisy-ycguo** [comment]
@pritidesai @mrutkows I made changes. Please review again. Now It is runnable in my environment.

**Comment by mrutkows** [comment]
@priti @daisy-ycguo I am tempted to merge this, but have asked @houshengbo to explain what the best approach would be to inject (guest) credentials for this and other test/use cases for automation in Travis CI.  We will want another issue to work on this automation and once working copy it for our other integration tests.

**Pull request merged**
