### PR TITLE
fix language:default runtime setting

### PR DESCRIPTION
**Pull request by TPei**
- add test for setting a runtime version to default

### CODE REVIEW

**Comment by rabbah** [comment]
Test looks good to me.

**Comment by rabbah** [comment]
Recording the test failure for convenience:
```
--- FAIL: TestComposeActionsForDefaultRuntimes (0.00s)
	manifest_parser_test.go:532: 
			Error Trace:	manifest_parser_test.go:532
			Error:      	Expected nil, but got: &wskderrors.InvalidRuntimeError{FileError:wskderrors.FileError{WskDeployBaseErr:wskderrors.WskDeployBaseErr{ErrorType:"ERROR_YAML_INVALID_RUNTIME", FileName:"manifest_parser.go", LineNum:735, Message:"Invalid or missing runtime [python:default] specified in manifest for the action [helloPython].\n Action [helloPython]: Runtime [python:default]: Supported Runtimes [php:7.1, php:7.2, php:7.3, ruby:2.5, go:1.11, dotnet:2.2, nodejs:6, nodejs:8, nodejs:10, python, python:2, python:3, swift:3.1.1, swift:4.1, swift:4.2, java]", MessageFormat:""}, ErrorFileName:"manifest_data_compose_runtimes_default.yaml", ErrorFilePath:"manifest_data_compose_runtimes_default.yaml"}, Runtime:"", SupportedRuntimes:[]string{"php:7.1", "php:7.2", "php:7.3", "ruby:2.5", "go:1.11", "dotnet:2.2", "nodejs:6", "nodejs:8", "nodejs:10", "python", "python:2", "python:3", "swift:3.1.1", "swift:4.1", "swift:4.2", "java"}}
			Test:       	TestComposeActionsForDefaultRuntimes
			Messages:   	Manifest [../tests/dat/manifest_data_compose_runtimes_default.yaml]: Failed to compose actions.
FAIL
```

**Comment by rabbah** [comment]
I'd like to resolve land this patch before the release I'm going to push next week. @TPei if you need help let me know.

**Comment by dgrove-oss** [comment]
@rabbah @TPei  -- is this ready to merge?  Looking at the discuss thread at https://lists.apache.org/thread.html/b9f79e9349a333dc83d2849a0eb016f313e3cc132b4ba6ca762bdbf9@%3Cdev.openwhisk.apache.org%3E it appears this is the last thing needed to merge before we can update the govendor hashes in the cli and proceed with a release.

**Pull request merged**
