### PR TITLE
Add the support to read env variable for package name

### PR DESCRIPTION
**Pull request by houshengbo**
Closes: #610

### CODE REVIEW

**Comment by pritidesai** [comment]
@houshengbo please add a sample manifest files with single and multiple packages:

```
packages:
   $package_name:
      actions:
         sample-action:
            function: sample-action.js
            inputs:
               param: value
```


```
packages:
   $package_name_1:
      actions:
         sample-action:
            function: sample-action.js
            inputs:
               param: value
   $package_name_2:
      actions:
         sample-action:
            function: sample-action.js
            inputs:
               param: value
```

**Comment by mrutkows** [comment]
@houshengbo thanks for adding additional tests for the "concatenation" of env. variable strings with in-line strings.

**Comment by mrutkows** [comment]
@houshengbo Priti brings up a validate request for an additional test(s) to assure it works on multiples (which it should looking at the code).

**Comment by houshengbo** [comment]
@pritidesai @mrutkows I have added the coverage of multiple packages.

**Pull request merged**
