### PR TITLE
Deprecating WithinOpenWhisk flag

### LINKED ISSUE #791: Crash when running with __OW_API_KEY and __OW_API_HOST set
I set those env vars to be able to run/debug actions locally and they appear to crash wskdeploy:

> SECMacbookPro:Dumper scottchapman$ wskdeploy
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/apache/incubator-openwhisk-wskdeploy/cmd.substCmdArgs(0x149c77c, 0x1a)
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:86 +0x3d6
> github.com/apache/incubator-openwhisk-wskdeploy/cmd.Execute()
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:61 +0xdb
> main.main()
> 	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/main.go:26 +0x20
>

### PR DESCRIPTION
**Pull request by pritidesai**
Closes #791

### CODE REVIEW

**Comment by mrutkows** [comment]
@beemarie Can you confirm that you no longer need to pass in arguments via a JSON structure when running 'wskdeploy' as an action.

**Comment by pritidesai** [comment]
@mrutkows based on the `exec` command from [package deploy](https://github.com/apache/incubator-openwhisk-package-deploy/blob/7e5bbeaa0c2e01c2b3a0bf66550f4d97fd1774eb/packages/actions/lib/common.js#L34), `wskdeploy` is running with:

```
command = `printf 'y' | ${__dirname}/../../wskdeploy -v -m ${manifestFileName} --auth ${wskAuth} --apihost ${wskApiHost}`;
```

Such as:

```
printf 'y' | /nodejsAction/SNbFbbD4/lib/../../wskdeploy -v -m manifest.yaml --auth <my-auth> --apihost https://172.17.0.1:443",
```

@beemarie please confirm.

**Comment by beemarie** [comment]
@pritidesai @mrutkows The code priti posted is how wskdeploy is being called from the deploy package.  The environment data (cloudant db, cloudant username, etc) is stored as execOptions for the exec command.  I don't know how that gets translated into the actual command, if it all?

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

Is it possible for you to test the deploy package with your change so we can be sure?

**Comment by pritidesai** [comment]
@beemarie `exec` deals with the set of env. variables specified in execOptions, its nothing to do with `wskdeploy`. Its more about injecting those env. variables (cloudant username etc) into env. where `wskdeploy` is being called:

```
exec env CLOUDANT_USERNAME=myusername /nodejsAction/SNbFbbD4/lib/../../wskdeploy -v -m manifest.yaml --auth <my-auth> --apihost https://172.17.0.1:443",
```

**Pull request merged**
