### PR TITLE
Remove top-level deprecated Package schema.

### PR DESCRIPTION
**Pull request by mrutkows**
This will remove deprecated keys:
- "package" at top-level
- "package" under "project"

In addition removing unit tests no longer needed, as well as invalid code that looked for credentials and namespace under "package".

Future PR will also remove deprecated key:
- "application" (in favor of "project")

### CODE REVIEW

**Comment by pritidesai** [comment]
@mrutkows the integration tests that you disabled looks good, we had added them for verifying `package` at top level which we are disabling now.

**Comment by pritidesai** [comment]
thanks Matt @mrutkows for clean up, we need to also remove `Package` from `YAML` struct here: https://github.com/mrutkows/incubator-openwhisk-wskdeploy/blob/5070701eba35155dbee4d914726c9ff750912d9c/parsers/yamlparser.go#L227

**Comment by mrutkows** [comment]
@pritidesai I thought I had removed all references (in fact I had to since I did remove "Package" from yamlparser.go.

**Comment by mrutkows** [comment]
@pritidesai complete removal causes the entire manifest_parser_test.go and all .yaml files it uses to be invalidated causing a complete rewrite of all these unit tests.

**Comment by mrutkows** [comment]
Opened issue: https://github.com/apache/incubator-openwhisk-wskdeploy/issues/749
to track unit test and 1 integration test that need rewrite.

**Comment by pritidesai** [comment]
Thanks a bunch @mrutkows 👍

**Pull request merged**
