### PR TITLE
Adjust unitary tests to it's correct path as the golang best practices.

### PR DESCRIPTION
**Pull request by lzbj**
Address issue #260.

### CODE REVIEW

**Comment by lzbj** [comment]
@daisy-ycguo ,please run `make test`.

**Comment by daisy-ycguo** [comment]
en..OK.
`go test ./... -tags=unit` works.

**Comment by daisy-ycguo** [comment]
Please see if `commands_test.go` should continue to stay at integration test folder. If it is a unit test, please change it to follow the unit test best practise.

**Comment by lzbj** [comment]
ah, sorry, I forgot this one, will update it.

**Comment by lzbj** [comment]
yes, update as per your comments.

**Pull request merged**
