### PR TITLE
Adding unit test cases for manifest_parser.go

### PR DESCRIPTION
**Pull request by pritidesai**

### CODE REVIEW

**Comment by houshengbo** [comment]
@pritidesai This PR needs to add the license header and fix the unit test failure.

**Comment by mrutkows** [comment]
Scancode error:
Scan detected 1 error(s) in 1 file(s):

  [/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/tools/travis/../../tests/usecases/helloworld/actions/Hello.java]:

       1: file does not include required license header.

Scan detected 1 error(s) in 1 file(s):

The command "./tools/travis/scancode.sh" exited with 1.

**Comment by pritidesai** [comment]
This PR is ready to merge, please help me merging it - Thanks!

**Comment by daisy-ycguo** [comment]
@pritidesai 

I run the unit test. One unit test cannot pass successfully. Please check. Thank you. Here is the output. 

```
?   	github.com/apache/incubator-openwhisk-wskdeploy	[no test files]
ok  	github.com/apache/incubator-openwhisk-wskdeploy/cmd	0.008s
ok  	github.com/apache/incubator-openwhisk-wskdeploy/deployers	0.020s
Error:  <nil>
Filepath: "  "
Package:  {   [] map[]     map[] map[] map[] map[] map[] map[] map[]}
PackageName: "  "
Number of Actions:  0
Actions:  map[]
--- **FAIL: TestComposeActionsForImplicitRuntimes** (0.00s)
        Error Trace:    manifest_parser_test.go:512
	Error:		Not equal: 
			expected: ""
			received: "nodejs:default"
	Messages:	Expected  but got nodejs:default
		
<nil>
[{param_float_value_only 3.14} {param_string_type_and_value_only foo} {param_string_type_only } {param_string_value_only foo} {param_int_value_only 123} {param_integer_type_only 0} {param_float_type_only 0} {param_string_with_default bar} {param_integer_with_default -1} {param_float_with_default 2.9}]
2017/08/22 02:35:39 open /home/daisy/gofolder/src/github.com/apache/incubator-openwhisk-wskdeploy/parsers/https://raw.githubusercontent.com/apache/incubator-openwhisk-wskdeploy/master/tests/usecases/helloworld/manifest.yaml: no such file or directory
2017/08/22 02:35:39 Error happened during execution, please type 'wskdeploy -h' for help messages.
FAIL	github.com/apache/incubator-openwhisk-wskdeploy/parsers	0.008s
?   	github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/common	[no test files]
ok  	github.com/apache/incubator-openwhisk-wskdeploy/utils	0.051s
?   	github.com/apache/incubator-openwhisk-wskdeploy/wski18n	[no test files]
```

**Comment by pritidesai** [comment]
@daisy-ycguo I have fixed the unit test which was failing, please merge this PR.

**Pull request merged**
