### PR TITLE
Deprecating Interactive Mode and introducing Preview

### LINKED ISSUE #693: whiskclient_test.go: "TestNewWhiskConfigInteractiveMode" incomplete/commented out
Either code the test (if valid/applicable/unique) or remove the commented out code.

### LINKED ISSUE #758: Deprecate interactive mode in wskdeploy
We started Whisk Deploy with interactive mode a year back but now, we have come long way from prototyping mode to running in production. As of now, we have no use case for Interactive mode, so from code maintenance perspective, we have decided to deprecate and remove support for interactive mode from Whisk Deploy.

### PR DESCRIPTION
**Pull request by pritidesai**
Closes #758 
Closes #693 

Introducing Preview:

```
./wskdeploy --preview -p tests/src/integration/helloworld/
Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [pdesai@us.ibm.com_dev], from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
Warning: The value for key [package version] is not saved in the current version of wskdeploy.
Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
Warning: The value for key [package version] is not saved in the current version of wskdeploy.
         ____      ___                   _    _ _     _     _
        /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
   /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
  /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
  \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\ 
   \___\/              |_|

Packages:
Name: IntegrationTestHelloWorld
    bindings: 

  * action: helloNodejsWithCode
    bindings: 
        - name : ""
        - place : ""
    annotations: 
  * action: helloJava
    bindings: 
        - name : "Bob"
    annotations: 
  * action: helloPython
    bindings: 
        - name : "Henry"
    annotations: 
  * action: helloPythonWithCode
    bindings: 
        - name : ""
    annotations: 
  * action: helloSwift
    bindings: 
        - name : ""
    annotations: 
  * action: helloSwiftWithCode
    bindings: 
        - name : ""
    annotations: 
  * action: helloNodejs
    bindings: 
        - name : "Amy"
        - place : "Paris"
    annotations: 

  * sequence: hello-world-series

Triggers:
* trigger: triggerHelloworld
    bindings: 
    annotations: 

 Rules
* rule: ruleMappingHelloworld
    - trigger: triggerHelloworld
    - action: IntegrationTestHelloWorld/hello-world-series

```

Undeployment Preview:

```
./wskdeploy undeploy --preview -p tests/src/integration/helloworld/
Info: The API host is [openwhisk.ng.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [pdesai@us.ibm.com_dev], from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.ng.bluemix.net.
Warning: The mandatory key [package version] should be set. Using default value [0.0.1]...
Warning: The value for key [package version] is not saved in the current version of wskdeploy.
Warning: The mandatory key [package license] should be set. Using default value [unlicensed]...
Warning: The value for key [package version] is not saved in the current version of wskdeploy.
         ____      ___                   _    _ _     _     _
        /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
   /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
  /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
  \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\ 
   \___\/              |_|

Packages:
Name: IntegrationTestHelloWorld
    bindings: 

  * action: helloJava
    bindings: 
        - name : "Bob"
    annotations: 
  * action: helloPython
    bindings: 
        - name : "Henry"
    annotations: 
  * action: helloPythonWithCode
    bindings: 
        - name : ""
    annotations: 
  * action: helloSwift
    bindings: 
        - name : ""
    annotations: 
  * action: helloSwiftWithCode
    bindings: 
        - name : ""
    annotations: 
  * action: helloNodejs
    bindings: 
        - name : "Amy"
        - place : "Paris"
    annotations: 
  * action: helloNodejsWithCode
    bindings: 
        - name : ""
        - place : ""
    annotations: 

  * sequence: hello-world-series

Triggers:
* trigger: triggerHelloworld
    bindings: 
    annotations: 

 Rules
* rule: ruleMappingHelloworld
    - trigger: triggerHelloworld
    - action: IntegrationTestHelloWorld/hello-world-series

```

### CODE REVIEW

**Comment by csantanapr** [comment]
What’s the target date to land dry run?

**Comment by mrutkows** [comment]
@pritidesai seeing "dry run" as a top-level command when export is avail (target file) and could be a variant (target screen); seems like it is an export variant… how hard would it be to make it a subcommand of export?  

In addition, "dry run" is a concept that may not translate well...

**Comment by mrutkows** [comment]
@pritidesai as we discussed, let us use "preview" as it is more formal and will not have any translation issues.

**Comment by pritidesai** [comment]
thanks @mrutkows I have renamed the flag, this PR is ready to merge.

**Comment by mrutkows** [comment]
@csantanapr today!

**Pull request merged**
